### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by belelabestia** [cartacodicesasso/ruotapazza#1]
Implementare un progetto ASP.NET Core (W C#) con `LanguageExt.Core`.

- [x] dotnet new
- [x] package add `LanguageExt.Core`
- [x] dotnet new xunit

## Obiettivo

Avere un backend con un endpoint funzionante e delle prove di utilizzo sensate di _LanguageExt_.

Prove di uso:

- gestione valori null/Option
- prove con liste/sequenze/altri tipi di liste
- esempio: lista di numeri nullable, se c'è un nullo errore altrimenti mappo a stringa

**Comment by mconstantine** [comment]
Closed with #5.
